kind: live
name: Run Filebrowser
author: Alexey Naiden
descr: runs Filebrowser

inputs:
  volumes_project_remote:
    descr: reference to a project remote
  http_port:
    descr: http port for filebrowser
    default: "80"
  http_auth:
    descr: whether to use http auth for jupter
    default: "True"
  job_name:
    default: "filebrowser"
    descr: |
      The name of filebrowser server.
      Use it to generate a predictable job hostname.
  preset:
    default: ""
    descr: |
      Resource preset used to run Filebrowser job. 
      Default: the first one in the `neuro config show` list.
  life_span:
    default: "1d"
    descr: |
      Amount of time to keep the Filebrowser job running.
      Format: "1d2h3m4s" (some parts may be missing).
      Default: 1 day. 

job:
    image: filebrowser/filebrowser:latest
    name: ${{ inputs.job_name }}
    http_port: $[[ inputs.http_port ]]
    http_auth: $[[ inputs.http_auth ]]
    life_span: $[[ inputs.life_span ]]
    preset: ${{ inputs.preset }}
    browse: True
    detach: True
    volumes:
      - $[[ inputs.volumes_project_remote ]]:/srv:rw
    cmd: --noauth --port ${{ inputs.http_port }}
